import type { Metadata } from "next";
import "./globals.css";

import { riamo, fahkwang } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${riamo.variable} ${fahkwang.variable} antialiased`}
      >
         
            {children}
      </body>
    </html>
  );
}
